version: '3.8'
name: "redis-manager"

networks:
    booking-network:
       driver: bridge


services:
    redis:
        image: redis:alpine
        ports:
           - "6379:6379"
        networks:
           - booking-network