version: '3.8'
name: "redis-manager"

networks:
  booking-network:
    driver: bridge

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - booking-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - booking-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: booking_service
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - booking-network

volumes:
  mysql_data:
